/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsultaRouteImport } from './routes/consulta'
import { Route as CancelarRouteImport } from './routes/cancelar'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGasRouteImport } from './routes/api/public/gas'

const ConsultaRoute = ConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelarRoute = CancelarRouteImport.update({
  id: '/cancelar',
  path: '/cancelar',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGasRoute = ApiPublicGasRouteImport.update({
  id: '/api/public/gas',
  path: '/api/public/gas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cancelar': typeof CancelarRoute
  '/consulta': typeof ConsultaRoute
  '/api/public/gas': typeof ApiPublicGasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cancelar': typeof CancelarRoute
  '/consulta': typeof ConsultaRoute
  '/api/public/gas': typeof ApiPublicGasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/cancelar': typeof CancelarRoute
  '/consulta': typeof ConsultaRoute
  '/api/public/gas': typeof ApiPublicGasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agendar' | '/cancelar' | '/consulta' | '/api/public/gas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agendar' | '/cancelar' | '/consulta' | '/api/public/gas'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/cancelar'
    | '/consulta'
    | '/api/public/gas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  CancelarRoute: typeof CancelarRoute
  ConsultaRoute: typeof ConsultaRoute
  ApiPublicGasRoute: typeof ApiPublicGasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/consulta': {
      id: '/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof ConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancelar': {
      id: '/cancelar'
      path: '/cancelar'
      fullPath: '/cancelar'
      preLoaderRoute: typeof CancelarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gas': {
      id: '/api/public/gas'
      path: '/api/public/gas'
      fullPath: '/api/public/gas'
      preLoaderRoute: typeof ApiPublicGasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  CancelarRoute: CancelarRoute,
  ConsultaRoute: ConsultaRoute,
  ApiPublicGasRoute: ApiPublicGasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
